return {
    {
        "catppuccin/nvim",
        lazy = true,
        enabled = true,
        name = "catppuccin",
        opts = {
            transparent_mode = false,
            integrations = {
                aerial = true,
                alpha = true,
                cmp = true,
                dashboard = true,
                flash = true,
                gitsigns = true,
                headlines = true,
                illuminate = true,
                indent_blankline = { enabled = true },
                leap = true,
                lsp_trouble = true,
                mason = true,
                markdown = true,
                mini = true,
                native_lsp = {
                    enabled = true,
                    underlines = {
                        errors = { "undercurl" },
                        hints = { "undercurl" },
                        warnings = { "undercurl" },
                        information = { "undercurl" },
                    },
                },
                navic = { enabled = true, custom_bg = "lualine" },
                neotest = true,
                neotree = true,
                noice = true,
                notify = true,
                semantic_tokens = true,
                telescope = true,
                treesitter = true,
                treesitter_context = true,
                which_key = true,
            },
        },
    },
    {
        "rebelot/kanagawa.nvim",
        enabled = false,
        lazy = true,
        priority = 1000,
    },
    {
        "Mofiqul/vscode.nvim",
        enabled = false,
        priority = 1000,
    },
    {
        "ribru17/bamboo.nvim",
        enabled = false,
        lazy = false,
        priority = 1000,
    },
}
